config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  root 'customer/homes#top'
  get 'about' => 'customer/homes#about'

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/comfirm' => 'orders#comfirm'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update'
    resources :orders, only: [:index ,:show, :update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, comfirm: 1, in_production: 2, ready_to_ship: 3, shipped: 4 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end

    def show
    end

    def edit
    end

    def update
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :check_admin, only: [:index, :show]

    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
        @order_details = OrderDetail.where(order_id: @order.id)
    end

    def update
        @order = Order.find(params[:id])
        if params[:order][:status] == 'comfirm'
            @order.update(status: (Order.statuses[params[:order][:status].to_sym]).to_i)
            order_details = OrderDetail.where(order_id: @order.id)
            order_details.each do |order_detail|
                order_detail.update(making_status: 1)
            end
            redirect_to admin_path
        else
            @order.update(status: params[:order][:status].to_i)
            redirect_to admin_path
        end
    end

    private

    def check_admin
        unless admin_signed_in?
            redirect_to root_path
        end
    end

    def order_params
        params.require(:order).permit(:id, :status)
    end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
    def index
        @address = Address.new
        @addresses = Address.all
    end

    def edit
        @address = Address.find(params[:id])
    end

    def create
        @address = Address.new(address_params)
        @address.customer_id = current_customer.id
        @address.save
        redirect_to addresses_path
    end

    def update
        @address = Address.find(params[:id])
        @address.update(address_params)
        redirect_to addresses_path
    end

    def destroy
        @address = Address.find(params[:id])
        @address.destroy
        redirect_to addresses_path
    end

    private

    def address_params
        params.require(:address).permit(:name, :postal_code, :address)
    end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
    def index
        @cart_item = CartItem.new
        @cart_items = CartItem.all
    end

    def update
        @cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
        @cart_item.amount = params[:cart_item][:amount].to_i
        @cart_item.save
        redirect_to cart_items_path
    end

    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        redirect_to cart_items_path
    end

    def destroy_all
        @cart_items = CartItem.where(customer_id: current_customer.id)
        @cart_items.destroy_all
        redirect_to cart_items_path
    end

    def create
        if current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
            @cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
            @cart_item.amount += params[:cart_item][:amount].to_i
            @cart_item.save
            redirect_to cart_items_path
        else
            @cart_item = CartItem.new(cart_item_params)
            @cart_item.customer_id = current_customer.id
            @cart_item.save
            redirect_to cart_items_path
        end
    end

    private
    def cart_item_params
        params.require(:cart_item).permit(:item_id, :amount)
    end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
    def show
    end

    def edit
    end

    def update
    end

    def unsubscribe
    end

    def withdraw
        current_customer.update(is_deleted: true)
        reset_session
        redirect_to root_path
    end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
    def top
    end
    
    def about
    end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
    def index
        @items = Item.all
        @genres = Genre.all
        @items = @items.where(genre_id: params[:genre_id].to_i) if params[:genre_id].present?
    end
    
    def show
        @genres = Genre.all
        @item = Item.find(params[:id])
        @cart_item = CartItem.new
    end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
    before_action :comfirm_order_items, only: [:new]

    def new
        @order = Order.new
    end

    def comfirm
        @order_new = Order.new
        @order = Order.new
        @order.payment_method = params[:order][:payment_method].to_i
        @order.customer_id = current_customer.id
        @order.shipping_cost = 800
        @cart_items = CartItem.where(customer_id: current_customer.id)
        if  params[:order][:address_option] == "0"
            @order.postal_code = current_customer.postal_code
            @order.address = current_customer.address
            @order.name = current_customer.last_name + current_customer.first_name
            render :comfirm
        elsif params[:order][:address_option] == "1"
            address = Address.find(params[:order][:address_id])
            @order.postal_code = address.postal_code
            @order.address = address.address
            @order.name = address.name
            render :comfirm
        elsif params[:order][:address_option] == "2"
            @order.postal_code = params[:order][:postal_code]
            @order.address = params[:order][:address]
            @order.name = params[:order][:name]
            render :comfirm
        end
    end

    def complete
    end

    def create
        @order = Order.new(order_params)
        @order.save
        cart_items = CartItem.where(customer_id: current_customer.id)
        cart_items.each do |cart_item, order_detail|
            order_detail  = OrderDetail.new
            order_detail.order_id = @order.id
            order_detail.item_id = cart_item.item_id
            order_detail.price = cart_item.item.price
            order_detail.amount = cart_item.amount
            order_detail.save
        end
        @cart_items = CartItem.where(customer_id: current_customer.id)
        @cart_items.destroy_all
        redirect_to orders_complete_path
    end

    def index
    end

    def show
    end

    private

    def comfirm_order_items
        if current_customer.cart_items.exists?
        else
            redirect_to items_path
        end
    end

    def order_params
        params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :payment_method, :total_payment)
    end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :password])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    customers_my_page_path
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :configure_is_deleted?,  only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    customers_my_page_path # ログイン後に遷移するpathを設定
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  protected

  def configure_is_deleted?
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == true))
        redirect_to new_customer_registration_path, notice: "退会済みです。"
      end
    end
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/comfirm.html.erb
<div class="container">
  <dvi class="row">
    <div class="col-2"></div>
    <div class="col-2 bg-light h4">注文情報確認</div>
  </dvi>

  <div class="row">
    <div class="col">
      <table class="table mt-4 table-bordered">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>
          <tbody>
            <% total_cost = 0 %>
            <% @cart_items.each do |cart_item| %>
              <tr>
                <th><%= image_tag cart_item.item.image, size: "50x50" %><span class="mx-3"><%= cart_item.item.name %></span></th>
                <td><%= cart_item.item.with_tax_price %></td>
                <td><%= cart_item.amount %></td>
                <td><%= cart_item.subtotal %></td>
                <% total_cost += cart_item.subtotal %>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>

    <div class="col">
      <div class="table-responsive mt-4">
        <table class="table table-bordered">
          <td>送料　 </td>
          <th><%= @order.shipping_cost %></th>
        </table>
        <table class="table table-bordered">
          <td>商品合計</td>
          <th><%= total_cost %></th>
        </table>
        <table class="table table-bordered">
          <td>請求金額</td>
          <th><%= @order.total_payment = total_cost + @order.shipping_cost %></th>
        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="row mt-3">
      <div class="ml-5 font-weight-bold h4 col mr-2">支払い方法</div><div class="mt-2"><%= Order.payment_methods_i18n[@order.payment_method] %></div>
    </div>
  </div>

  <div class="row">
    <div class="row mt-3">
      <div class="ml-5 font-weight-bold h4 col mr-2">お届け先</div>
      <div class="mt-2">
        <%= '〒' + @order.postal_code + ' ' + @order.address %></br>
        <%= @order.name %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="m-5 col">
      <%= form_with model: @order, url: "/orders", method: :post do |f| %>
      <%= f.hidden_field :customer_id,    value: @order.customer_id %>
      <%= f.hidden_field :postal_code,    value: @order.postal_code %>
      <%= f.hidden_field :address,        value: @order.address %>
      <%= f.hidden_field :name,           value: @order.name %>
      <%= f.hidden_field :shipping_cost,  value: @order.shipping_cost %>
      <%= f.hidden_field :total_payment,  value: @order.total_payment %>
      <%= f.hidden_field :payment_method, value: @order.payment_method %>
      <%= f.submit "注文を確定する", class: "btn btn-success", data: { confirm: "注文を確定しますか？" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/complete.html.erb
<div class="container">
  <div class="d-flex align-items-center h4 justify-content-center" style="height:400px;">
    ご注文ありがとうございました！
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-1"></div>
    <div class="col-2 h4 bg-light m-3">注文情報入力</div>
  </div>

  <%= form_with model: @order, url: orders_comfirm_path, method: :post, local: true do |f| %>

  <div class="row mt-2">
    <div class="ml-5 font-weight-bold h5">支払い方法</div>
  </div>
  <div class="row mx-5">
    <div>
      <%= f.radio_button :payment_method, 0, checked: true %><%= f.label :payment_method, Order.payment_methods_i18n[:credit_card], class: "ml-3" %>
      <div></div>
      <%= f.radio_button :payment_method, 1 %><%= f.label :payment_method, Order.payment_methods_i18n[:transfer], class: "ml-3" %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="ml-5 font-weight-bold h5">お届け先</div>
  </div>
  <div class="row mx-5">
    <div>
      <%= f.radio_button :address_option, 0, checked: true %><span class="ml-3">ご自身の住所</span></br>
      <div class="mt-2 mx-4 mb-4">
        <%= '〒' + current_customer.postal_code + ' ' + current_customer.address %></br>
        <%= current_customer.last_name + current_customer.first_name %>
      </div>
      <%= f.radio_button :address_option, 1 %><span class="ml-3">登録住所から選択</span>
      <div class="mt-2 mx-4 mb-4">
        <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :full_address) %>
      </div>
      <%= f.radio_button :address_option, 2 %><span class="ml-3">新しいお届け先</span>
      <div class="mt-2 mx-4 mb-4">
        <div class="field m-2">
            <%= f.label :postal_code, "郵便番号（ハイフンなし）　" %><%= f.text_field :postal_code, autofocus: true %>
          </div>

          <div class="field m-2">
            <%= f.label :address, "住所　　　　　　　　　　　" %><%= f.text_field :address, autofocus: true %>
          </div>

           <div class="field m-2">
            <%= f.label :name, "宛名　　　　　　　　　　　" %><%= f.text_field :name, autofocus: true %>
          </div>
      </div>

      <div><%= f.submit '確認画面へ進む', class: "mx-auto btn btn-primary" %></div>
    </div>

  <% end %>
</div>