config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  root 'customer/homes#top'
  get 'about' => 'customer/homes#about'

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/comfirm' => 'orders#comfirm'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update'
    resources :orders, only: [:index ,:show, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    
    has_many :cart_items
    has_many :order_details
    belongs_to :genre

    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, comfirm: 1, in_production: 2, ready_to_ship: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { couldnt_make: 0, waiting_for_production: 1, in_production: 2, completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genre = Genre.new
        @genres = Genre.all
    end

    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to admin_genres_path
    end

    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        @genre = Genre.find(params[:id])
        if @genre.update(genre_params)
            redirect_to admin_genres_path, notice: "You have updated genre successfully."
        else
            render "edit"
        end
    end

    private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/genres/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto col-11 col-lg-8 col-xl-6">

        <nav class="navbar navbar-light bg-light m-auto">
          <div class="container-fluid">ジャンル編集</div>
        </nav>

        <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
        <%= f.label :name, "ジャンル名" %><%= f.text_field :name, autofocus: true, class: "ml-3" %>
        <%= f.submit "変更を保存", class: "btn btn-success m-3" %>
        <% end %>
        <div></div>

    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto col-11 col-lg-8 col-xl-6">

        <nav class="navbar navbar-light bg-light m-auto">
          <div class="container-fluid">ジャンル一覧・追加</div>
        </nav>

        <%= form_with model: @genre, url: "/admin/genres",local: true do |f| %>
        <%= f.label :name, "ジャンル名"%><%= f.text_field :name, autofocus: true, class: "ml-3" %>
        <%= f.submit "新規登録", class: "btn btn-success m-3" %>
        <% end %>
        <div></div>

        <table class="table m-3">
          <tbody>
            <tr>
              <th scope="row">ジャンル</th>
              <td></td>
            </tr>
            <% @genres.each do |genre| %>
            <tr>
              <th scope="row"><%= genre.name %></th>
              <td><%= link_to '編集する', edit_admin_genre_path(genre), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  </div>
</div>